from __future__ import annotations

from typing import Any

from app.core.config import Settings

PROVIDER_DEFINITIONS: list[dict[str, Any]] = [
    {
        "id": "ipapi.is",
        "name": "ipapi.is",
        "enabled": True,
        "role": "primary",
        "fallback_phase": "primary",
        "endpoint": "https://api.ipapi.is",
        "requires_key": False,
        "key_name": "ipapi_is_key",
        "provides": [
            "ip",
            "country",
            "country_code",
            "region",
            "city",
            "asn",
            "asn_owner",
            "org",
            "isp",
            "latitude",
            "longitude",
            "network_type",
            "registry",
            "reg_region",
            "asn_domain",
            "org_domain",
            "is_proxy",
            "is_vpn",
            "is_tor",
            "is_mobile",
            "is_hosting",
            "is_crawler",
            "is_abuser",
        ],
        "field_paths": {
            "network_type": ["company.type", "asn.type"],
            "is_hosting": ["is_datacenter", "is_hosting", "hosting", "security.is_datacenter", "privacy.is_datacenter"],
            "is_proxy": ["is_proxy", "proxy", "security.proxy", "privacy.proxy"],
            "is_vpn": ["is_vpn", "vpn", "security.vpn", "privacy.vpn"],
            "is_tor": ["is_tor", "tor", "security.tor", "privacy.tor"],
            "is_mobile": ["is_mobile", "mobile"],
            "is_crawler": ["is_crawler", "crawler"],
            "is_abuser": ["is_abuser", "abuser"],
        },
    },
    {
        "id": "ipwho.is",
        "name": "ipwho.is",
        "enabled": True,
        "role": "basic fallback",
        "fallback_phase": "basic",
        "endpoint": "https://ipwho.is/{ip}",
        "requires_key": False,
        "key_name": None,
        "provides": [
            "ip",
            "country",
            "country_code",
            "region",
            "city",
            "asn",
            "asn_owner",
            "org",
            "isp",
            "latitude",
            "longitude",
            "network_type",
            "asn_domain",
            "org_domain",
            "is_proxy",
            "is_vpn",
            "is_tor",
            "is_hosting",
            "is_crawler",
            "is_abuser",
        ],
        "field_paths": {
            "network_type": ["connection.type", "connection.connection_type"],
            "is_proxy": ["security.proxy", "security.is_proxy"],
            "is_vpn": ["security.vpn", "security.is_vpn"],
            "is_tor": ["security.tor", "security.is_tor"],
            "is_hosting": ["security.hosting", "security.is_hosting"],
            "is_crawler": ["security.crawler", "security.is_crawler"],
            "is_abuser": ["security.abuser", "security.is_abuser", "security.threat", "security.is_threat"],
        },
    },
    {
        "id": "ip-api.com",
        "name": "ip-api.com",
        "enabled": True,
        "role": "basic fallback",
        "fallback_phase": "basic",
        "endpoint": "http://ip-api.com/json/{ip}",
        "requires_key": False,
        "key_name": None,
        "provides": [
            "ip",
            "country",
            "country_code",
            "region",
            "city",
            "asn",
            "asn_owner",
            "org",
            "isp",
            "latitude",
            "longitude",
            "is_proxy",
            "is_mobile",
            "is_hosting",
        ],
        "field_paths": {
            "is_proxy": ["proxy"],
            "is_mobile": ["mobile"],
            "is_hosting": ["hosting"],
        },
    },
    {
        "id": "ipapi.org",
        "name": "ipapi.org",
        "enabled": True,
        "role": "basic fallback",
        "fallback_phase": "basic",
        "endpoint": "https://ipapi.org/api/ip/{ip}",
        "requires_key": False,
        "key_name": "ipapi_org_key",
        "provides": [
            "ip",
            "country",
            "country_code",
            "region",
            "city",
            "asn",
            "asn_owner",
            "org",
            "isp",
            "latitude",
            "longitude",
        ],
        "field_paths": {},
    },
    {
        "id": "ipinfo.io",
        "name": "ipinfo.io",
        "enabled": True,
        "role": "domain fallback",
        "fallback_phase": "asn_domain",
        "endpoint": "https://ipinfo.io/{ip}/json",
        "requires_key": False,
        "key_name": "ipinfo_token",
        "provides": [
            "ip",
            "country",
            "region",
            "city",
            "asn",
            "org",
            "isp",
            "latitude",
            "longitude",
            "network_type",
            "asn_domain",
        ],
        "field_paths": {
            "network_type": ["asn.type", "network_type"],
        },
    },
    {
        "id": "ipdata.co",
        "name": "ipdata.co",
        "enabled": True,
        "role": "domain/security fallback",
        "fallback_phase": "asn_domain",
        "endpoint": "https://api.ipdata.co/{ip}",
        "requires_key": False,
        "key_name": "ipdata_key",
        "provides": [
            "ip",
            "country",
            "country_code",
            "region",
            "city",
            "asn",
            "asn_owner",
            "org",
            "isp",
            "latitude",
            "longitude",
            "network_type",
            "asn_domain",
            "is_proxy",
            "is_vpn",
            "is_tor",
            "is_hosting",
            "is_abuser",
        ],
        "field_paths": {
            "network_type": ["asn.type", "network_type", "usage_type"],
            "is_proxy": ["threat.is_proxy", "threat.is_anonymous", "threat.is_icloud"],
            "is_vpn": ["threat.is_vpn"],
            "is_tor": ["threat.is_tor"],
            "is_hosting": ["threat.is_datacenter", "threat.is_cloud_provider"],
            "is_abuser": [
                "threat.is_known_attacker",
                "threat.is_known_abuser",
                "threat.is_abuser",
                "threat.is_threat",
                "threat.is_spam",
            ],
        },
    },
]

FIELD_DEFINITIONS: list[dict[str, Any]] = [
    {
        "field": "network_type",
        "label": "网络类型",
        "source_type": "provider_structured",
        "scoring": True,
        "used_for": ["ip_property", "risk_confidence", "humanbot_confidence"],
        "providers": {
            "ipapi.is": ["company.type", "asn.type"],
            "ipwho.is": ["connection.type", "connection.connection_type"],
            "ipinfo.io": ["asn.type", "network_type"],
            "ipdata.co": ["asn.type", "network_type", "usage_type"],
        },
    },
    {
        "field": "is_hosting",
        "label": "托管/机房信号",
        "source_type": "provider_structured",
        "scoring": True,
        "used_for": ["ip_property", "risk_score", "humanbot"],
        "providers": {
            "ipapi.is": ["is_datacenter", "is_hosting", "hosting"],
            "ipwho.is": ["security.hosting", "security.is_hosting"],
            "ip-api.com": ["hosting"],
            "ipdata.co": ["threat.is_datacenter", "threat.is_cloud_provider"],
        },
    },
    {
        "field": "is_proxy",
        "label": "代理信号",
        "source_type": "provider_structured",
        "scoring": True,
        "used_for": ["risk_score", "humanbot"],
        "providers": {
            "ipapi.is": ["is_proxy", "proxy", "security.proxy", "privacy.proxy"],
            "ipwho.is": ["security.proxy", "security.is_proxy"],
            "ip-api.com": ["proxy"],
            "ipdata.co": ["threat.is_proxy", "threat.is_anonymous", "threat.is_icloud"],
        },
    },
    {
        "field": "is_vpn",
        "label": "VPN 信号",
        "source_type": "provider_structured",
        "scoring": True,
        "used_for": ["risk_score", "humanbot"],
        "providers": {
            "ipapi.is": ["is_vpn", "vpn", "security.vpn", "privacy.vpn"],
            "ipwho.is": ["security.vpn", "security.is_vpn"],
            "ipdata.co": ["threat.is_vpn"],
        },
    },
    {
        "field": "is_tor",
        "label": "TOR 信号",
        "source_type": "provider_structured",
        "scoring": True,
        "used_for": ["risk_score", "humanbot"],
        "providers": {
            "ipapi.is": ["is_tor", "tor", "security.tor", "privacy.tor"],
            "ipwho.is": ["security.tor", "security.is_tor"],
            "ipdata.co": ["threat.is_tor"],
        },
    },
    {
        "field": "is_mobile",
        "label": "移动网络信号",
        "source_type": "provider_structured",
        "scoring": True,
        "used_for": ["ip_property_home_leaning", "risk_discount", "confidence"],
        "providers": {
            "ipapi.is": ["is_mobile", "mobile"],
            "ip-api.com": ["mobile"],
        },
    },
    {
        "field": "is_crawler",
        "label": "爬虫信号",
        "source_type": "provider_structured",
        "scoring": True,
        "used_for": ["risk_score", "humanbot"],
        "providers": {
            "ipapi.is": ["is_crawler", "crawler"],
            "ipwho.is": ["security.crawler", "security.is_crawler"],
        },
    },
    {
        "field": "is_abuser",
        "label": "滥用信号",
        "source_type": "provider_structured",
        "scoring": True,
        "used_for": ["risk_score", "humanbot"],
        "providers": {
            "ipapi.is": ["is_abuser", "abuser"],
            "ipwho.is": ["security.abuser", "security.is_abuser", "security.threat", "security.is_threat"],
            "ipdata.co": [
                "threat.is_known_attacker",
                "threat.is_known_abuser",
                "threat.is_abuser",
                "threat.is_threat",
                "threat.is_spam",
            ],
        },
    },
    {
        "field": "ip_source",
        "label": "原生/广播 IP",
        "source_type": "derived",
        "scoring": True,
        "used_for": ["risk_score"],
        "providers": {
            "derived": ["reg_region", "country_code", "country"],
        },
    },
    {
        "field": "isp",
        "label": "ISP/运营商",
        "source_type": "identity_text",
        "scoring": False,
        "used_for": ["display", "compatibility"],
        "providers": {
            "ipapi.is": ["isp", "company.name", "asn.name", "asn.org"],
            "ipwho.is": ["connection.isp", "connection.org"],
            "ip-api.com": ["isp", "org"],
            "ipapi.org": ["isp", "org", "asn.name"],
            "ipinfo.io": ["org", "hostname"],
            "ipdata.co": ["asn.name", "organisation", "isp"],
        },
    },
    {
        "field": "org",
        "label": "企业/组织",
        "source_type": "identity_text",
        "scoring": False,
        "used_for": ["display", "compatibility"],
        "providers": {},
    },
    {
        "field": "asn_owner",
        "label": "ASN 所有者",
        "source_type": "identity_text",
        "scoring": False,
        "used_for": ["display", "compatibility"],
        "providers": {},
    },
    {
        "field": "asn_domain",
        "label": "ASN 域名",
        "source_type": "identity_text",
        "scoring": False,
        "used_for": ["display", "link"],
        "providers": {},
    },
    {
        "field": "org_domain",
        "label": "企业域名",
        "source_type": "identity_text",
        "scoring": False,
        "used_for": ["display", "link"],
        "providers": {},
    },
]


def admin_settings(settings: Settings) -> dict[str, Any]:
    return {"keys": settings.key_status(), "config": settings.public_config()}


def admin_providers(settings: Settings) -> list[dict[str, Any]]:
    key_status = settings.key_status()
    timeout = settings.myip_provider_timeout_seconds
    providers: list[dict[str, Any]] = []
    for index, definition in enumerate(PROVIDER_DEFINITIONS, start=1):
        provider = dict(definition)
        key_name = provider["key_name"]
        provider["order"] = index
        provider["timeout_seconds"] = timeout
        provider["key_configured"] = bool(key_name and key_status[key_name]["configured"])
        providers.append(provider)
    return providers


def admin_fields() -> list[dict[str, Any]]:
    return FIELD_DEFINITIONS
